//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CCDataInterfaceService.CCDataInterfaceServiceSoap")]
    public interface CCDataInterfaceServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCallDataHuiMC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCallDataHuiMC(out int totalCount, string Verifycode, string starttime, string endtime, int currentPage, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInboundDataHuiMC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetInboundDataHuiMC(out int totalCount, string Verifycode, string starttime, string endtime, int currentPage, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWorkOrderInfoHMC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetWorkOrderInfoHMC(out int totalCount, string Verifycode, BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.QueryWorkOrderInfo query, int currentPage, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCallDataByCallIDHuiMC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.CallRecord_ORIG GetCallDataByCallIDHuiMC(string Verifycode, long callid, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCallData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCallData(out int totalCount, string Verifycode, BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.CallRecord_ORIGCondition query, int PageIndex, int PageSize, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCallDataByCallID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.CallRecord_ORIG GetCallDataByCallID(string Verifycode, long callid, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CCDataInterface_InsertCustData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CCDataInterface_InsertCustData(out string CustID, out string msg, string Verifycode, string jsonDataStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CCDataInterface_GetCustHistoryInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable CCDataInterface_GetCustHistoryInfo(out int totalCount, string Verifycode, int userid, BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.QueryCustHistoryInfo query, int currentPage, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeAgentInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetEmployeeAgentInfo(string Verifycode, int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustBasicInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCustBasicInfo(string Verifycode, string tel, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAddWOrderComeIn_IMGR_URL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAddWOrderComeIn_IMGR_URL(string Verifycode, BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.CallSourceEnum callsource, string phone, long csid, string cbname, int cbsex, int province, int city, int county, int businesstype, int businesstag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAddWOrderComeIn_IMJXS_NC_URL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAddWOrderComeIn_IMJXS_NC_URL(string Verifycode, BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.CallSourceEnum callsource, string phone, long csid, string cbname, int cbsex, int province, int city, int county, string membercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAddWOrderComeIn_IMJXS_SC_URL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAddWOrderComeIn_IMJXS_SC_URL(string Verifycode, BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.CallSourceEnum callsource, string phone, long csid, string cbname, int cbsex, int province, int city, int county, string membercode);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryWorkOrderInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int tagBGIDField;
        
        private string orderIDField;
        
        private int categoryIDField;
        
        private System.Nullable<int> dataSourceField;
        
        private string custNameField;
        
        private string cRMCustIDField;
        
        private System.Nullable<int> provinceIDField;
        
        private System.Nullable<int> cityIDField;
        
        private System.Nullable<int> countyIDField;
        
        private string contactField;
        
        private string contactTelField;
        
        private System.Nullable<int> priorityLevelField;
        
        private string lastProcessDateField;
        
        private bool isComplaintTypeField;
        
        private string titleField;
        
        private System.Nullable<int> workOrderStatusField;
        
        private string contentField;
        
        private System.Nullable<int> receiverIDField;
        
        private string receiverNameField;
        
        private string receiverDepartNameField;
        
        private bool isSalesField;
        
        private System.Nullable<int> attentionCarBrandIDField;
        
        private System.Nullable<int> attentionCarSerialIDField;
        
        private System.Nullable<int> attentionCarTypeIDField;
        
        private string attentionCarBrandNameField;
        
        private string attentionCarSerialNameField;
        
        private string attentionCarTypeNameField;
        
        private string selectDealerIDField;
        
        private string selectDealerNameField;
        
        private System.Nullable<int> isReturnVisitField;
        
        private string nominateActivityField;
        
        private System.Nullable<int> saleCarBrandIDField;
        
        private System.Nullable<int> saleCarSerialIDField;
        
        private System.Nullable<int> saleCarTypeIDField;
        
        private string saleCarBrandNameField;
        
        private string saleCarSerialNameField;
        
        private string saleCarTypeNameField;
        
        private System.Nullable<int> statusField;
        
        private bool isRevertField;
        
        private System.Nullable<System.DateTime> createTimeField;
        
        private string createUserNameField;
        
        private System.Nullable<int> createUserIDField;
        
        private System.Nullable<System.DateTime> modifyTimeField;
        
        private System.Nullable<int> modifyUserIDField;
        
        private string beginCreateTimeField;
        
        private string endCreateTimeField;
        
        private string isRevertStrField;
        
        private int rightTypeField;
        
        private int custCategoryIDField;
        
        private string isReCheckField;
        
        private System.Nullable<int> workCategoryField;
        
        private string areaIDField;
        
        private int bGIDField;
        
        private int sCIDField;
        
        private int loginIDField;
        
        private string demandIDField;
        
        private int tagIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TagBGID {
            get {
                return this.tagBGIDField;
            }
            set {
                this.tagBGIDField = value;
                this.RaisePropertyChanged("TagBGID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
                this.RaisePropertyChanged("OrderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CategoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
                this.RaisePropertyChanged("CategoryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> DataSource {
            get {
                return this.dataSourceField;
            }
            set {
                this.dataSourceField = value;
                this.RaisePropertyChanged("DataSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CustName {
            get {
                return this.custNameField;
            }
            set {
                this.custNameField = value;
                this.RaisePropertyChanged("CustName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CRMCustID {
            get {
                return this.cRMCustIDField;
            }
            set {
                this.cRMCustIDField = value;
                this.RaisePropertyChanged("CRMCustID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> ProvinceID {
            get {
                return this.provinceIDField;
            }
            set {
                this.provinceIDField = value;
                this.RaisePropertyChanged("ProvinceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> CityID {
            get {
                return this.cityIDField;
            }
            set {
                this.cityIDField = value;
                this.RaisePropertyChanged("CityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> CountyID {
            get {
                return this.countyIDField;
            }
            set {
                this.countyIDField = value;
                this.RaisePropertyChanged("CountyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
                this.RaisePropertyChanged("Contact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ContactTel {
            get {
                return this.contactTelField;
            }
            set {
                this.contactTelField = value;
                this.RaisePropertyChanged("ContactTel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> PriorityLevel {
            get {
                return this.priorityLevelField;
            }
            set {
                this.priorityLevelField = value;
                this.RaisePropertyChanged("PriorityLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string LastProcessDate {
            get {
                return this.lastProcessDateField;
            }
            set {
                this.lastProcessDateField = value;
                this.RaisePropertyChanged("LastProcessDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool IsComplaintType {
            get {
                return this.isComplaintTypeField;
            }
            set {
                this.isComplaintTypeField = value;
                this.RaisePropertyChanged("IsComplaintType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<int> WorkOrderStatus {
            get {
                return this.workOrderStatusField;
            }
            set {
                this.workOrderStatusField = value;
                this.RaisePropertyChanged("WorkOrderStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<int> ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
                this.RaisePropertyChanged("ReceiverID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ReceiverName {
            get {
                return this.receiverNameField;
            }
            set {
                this.receiverNameField = value;
                this.RaisePropertyChanged("ReceiverName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ReceiverDepartName {
            get {
                return this.receiverDepartNameField;
            }
            set {
                this.receiverDepartNameField = value;
                this.RaisePropertyChanged("ReceiverDepartName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool IsSales {
            get {
                return this.isSalesField;
            }
            set {
                this.isSalesField = value;
                this.RaisePropertyChanged("IsSales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<int> AttentionCarBrandID {
            get {
                return this.attentionCarBrandIDField;
            }
            set {
                this.attentionCarBrandIDField = value;
                this.RaisePropertyChanged("AttentionCarBrandID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<int> AttentionCarSerialID {
            get {
                return this.attentionCarSerialIDField;
            }
            set {
                this.attentionCarSerialIDField = value;
                this.RaisePropertyChanged("AttentionCarSerialID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<int> AttentionCarTypeID {
            get {
                return this.attentionCarTypeIDField;
            }
            set {
                this.attentionCarTypeIDField = value;
                this.RaisePropertyChanged("AttentionCarTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string AttentionCarBrandName {
            get {
                return this.attentionCarBrandNameField;
            }
            set {
                this.attentionCarBrandNameField = value;
                this.RaisePropertyChanged("AttentionCarBrandName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string AttentionCarSerialName {
            get {
                return this.attentionCarSerialNameField;
            }
            set {
                this.attentionCarSerialNameField = value;
                this.RaisePropertyChanged("AttentionCarSerialName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string AttentionCarTypeName {
            get {
                return this.attentionCarTypeNameField;
            }
            set {
                this.attentionCarTypeNameField = value;
                this.RaisePropertyChanged("AttentionCarTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string SelectDealerID {
            get {
                return this.selectDealerIDField;
            }
            set {
                this.selectDealerIDField = value;
                this.RaisePropertyChanged("SelectDealerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string SelectDealerName {
            get {
                return this.selectDealerNameField;
            }
            set {
                this.selectDealerNameField = value;
                this.RaisePropertyChanged("SelectDealerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<int> IsReturnVisit {
            get {
                return this.isReturnVisitField;
            }
            set {
                this.isReturnVisitField = value;
                this.RaisePropertyChanged("IsReturnVisit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string NominateActivity {
            get {
                return this.nominateActivityField;
            }
            set {
                this.nominateActivityField = value;
                this.RaisePropertyChanged("NominateActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<int> SaleCarBrandID {
            get {
                return this.saleCarBrandIDField;
            }
            set {
                this.saleCarBrandIDField = value;
                this.RaisePropertyChanged("SaleCarBrandID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public System.Nullable<int> SaleCarSerialID {
            get {
                return this.saleCarSerialIDField;
            }
            set {
                this.saleCarSerialIDField = value;
                this.RaisePropertyChanged("SaleCarSerialID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public System.Nullable<int> SaleCarTypeID {
            get {
                return this.saleCarTypeIDField;
            }
            set {
                this.saleCarTypeIDField = value;
                this.RaisePropertyChanged("SaleCarTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string SaleCarBrandName {
            get {
                return this.saleCarBrandNameField;
            }
            set {
                this.saleCarBrandNameField = value;
                this.RaisePropertyChanged("SaleCarBrandName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string SaleCarSerialName {
            get {
                return this.saleCarSerialNameField;
            }
            set {
                this.saleCarSerialNameField = value;
                this.RaisePropertyChanged("SaleCarSerialName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string SaleCarTypeName {
            get {
                return this.saleCarTypeNameField;
            }
            set {
                this.saleCarTypeNameField = value;
                this.RaisePropertyChanged("SaleCarTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public System.Nullable<int> Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public bool IsRevert {
            get {
                return this.isRevertField;
            }
            set {
                this.isRevertField = value;
                this.RaisePropertyChanged("IsRevert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=39)]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
                this.RaisePropertyChanged("CreateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string CreateUserName {
            get {
                return this.createUserNameField;
            }
            set {
                this.createUserNameField = value;
                this.RaisePropertyChanged("CreateUserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=41)]
        public System.Nullable<int> CreateUserID {
            get {
                return this.createUserIDField;
            }
            set {
                this.createUserIDField = value;
                this.RaisePropertyChanged("CreateUserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=42)]
        public System.Nullable<System.DateTime> ModifyTime {
            get {
                return this.modifyTimeField;
            }
            set {
                this.modifyTimeField = value;
                this.RaisePropertyChanged("ModifyTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=43)]
        public System.Nullable<int> ModifyUserID {
            get {
                return this.modifyUserIDField;
            }
            set {
                this.modifyUserIDField = value;
                this.RaisePropertyChanged("ModifyUserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string BeginCreateTime {
            get {
                return this.beginCreateTimeField;
            }
            set {
                this.beginCreateTimeField = value;
                this.RaisePropertyChanged("BeginCreateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string EndCreateTime {
            get {
                return this.endCreateTimeField;
            }
            set {
                this.endCreateTimeField = value;
                this.RaisePropertyChanged("EndCreateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string IsRevertStr {
            get {
                return this.isRevertStrField;
            }
            set {
                this.isRevertStrField = value;
                this.RaisePropertyChanged("IsRevertStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public int RightType {
            get {
                return this.rightTypeField;
            }
            set {
                this.rightTypeField = value;
                this.RaisePropertyChanged("RightType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public int CustCategoryID {
            get {
                return this.custCategoryIDField;
            }
            set {
                this.custCategoryIDField = value;
                this.RaisePropertyChanged("CustCategoryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string IsReCheck {
            get {
                return this.isReCheckField;
            }
            set {
                this.isReCheckField = value;
                this.RaisePropertyChanged("IsReCheck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=50)]
        public System.Nullable<int> WorkCategory {
            get {
                return this.workCategoryField;
            }
            set {
                this.workCategoryField = value;
                this.RaisePropertyChanged("WorkCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string AreaID {
            get {
                return this.areaIDField;
            }
            set {
                this.areaIDField = value;
                this.RaisePropertyChanged("AreaID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public int BGID {
            get {
                return this.bGIDField;
            }
            set {
                this.bGIDField = value;
                this.RaisePropertyChanged("BGID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public int SCID {
            get {
                return this.sCIDField;
            }
            set {
                this.sCIDField = value;
                this.RaisePropertyChanged("SCID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public int LoginID {
            get {
                return this.loginIDField;
            }
            set {
                this.loginIDField = value;
                this.RaisePropertyChanged("LoginID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string DemandID {
            get {
                return this.demandIDField;
            }
            set {
                this.demandIDField = value;
                this.RaisePropertyChanged("DemandID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public int TagID {
            get {
                return this.tagIDField;
            }
            set {
                this.tagIDField = value;
                this.RaisePropertyChanged("TagID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryCustHistoryInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long recIDField;
        
        private string taskIDField;
        
        private long callRecordIDField;
        
        private string custIDField;
        
        private System.Nullable<int> recordTypeField;
        
        private System.Nullable<int> consultIDField;
        
        private System.Nullable<int> consultDataIDField;
        
        private System.Nullable<int> questionQualityField;
        
        private System.Nullable<System.DateTime> lastTreatmentTimeField;
        
        private bool isComplaintField;
        
        private System.Nullable<int> processStatusField;
        
        private string processStatusStrField;
        
        private bool isSendEmailField;
        
        private System.Nullable<System.DateTime> createTimeField;
        
        private System.Nullable<int> createUserIDField;
        
        private string beginTimeField;
        
        private string endTimeField;
        
        private System.Nullable<int> consultDCoopTypeField;
        
        private string questionTypeField;
        
        private string custNameField;
        
        private string statusField;
        
        private string isCompaintStrField;
        
        private string isIsSendEmailStrField;
        
        private string rightStrField;
        
        private string consultIDStrField;
        
        private string questionQualityStrField;
        
        private string isForwardingStrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long RecID {
            get {
                return this.recIDField;
            }
            set {
                this.recIDField = value;
                this.RaisePropertyChanged("RecID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TaskID {
            get {
                return this.taskIDField;
            }
            set {
                this.taskIDField = value;
                this.RaisePropertyChanged("TaskID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long CallRecordID {
            get {
                return this.callRecordIDField;
            }
            set {
                this.callRecordIDField = value;
                this.RaisePropertyChanged("CallRecordID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CustID {
            get {
                return this.custIDField;
            }
            set {
                this.custIDField = value;
                this.RaisePropertyChanged("CustID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> RecordType {
            get {
                return this.recordTypeField;
            }
            set {
                this.recordTypeField = value;
                this.RaisePropertyChanged("RecordType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> ConsultID {
            get {
                return this.consultIDField;
            }
            set {
                this.consultIDField = value;
                this.RaisePropertyChanged("ConsultID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> ConsultDataID {
            get {
                return this.consultDataIDField;
            }
            set {
                this.consultDataIDField = value;
                this.RaisePropertyChanged("ConsultDataID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> QuestionQuality {
            get {
                return this.questionQualityField;
            }
            set {
                this.questionQualityField = value;
                this.RaisePropertyChanged("QuestionQuality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> LastTreatmentTime {
            get {
                return this.lastTreatmentTimeField;
            }
            set {
                this.lastTreatmentTimeField = value;
                this.RaisePropertyChanged("LastTreatmentTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsComplaint {
            get {
                return this.isComplaintField;
            }
            set {
                this.isComplaintField = value;
                this.RaisePropertyChanged("IsComplaint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> ProcessStatus {
            get {
                return this.processStatusField;
            }
            set {
                this.processStatusField = value;
                this.RaisePropertyChanged("ProcessStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ProcessStatusStr {
            get {
                return this.processStatusStrField;
            }
            set {
                this.processStatusStrField = value;
                this.RaisePropertyChanged("ProcessStatusStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool IsSendEmail {
            get {
                return this.isSendEmailField;
            }
            set {
                this.isSendEmailField = value;
                this.RaisePropertyChanged("IsSendEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
                this.RaisePropertyChanged("CreateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> CreateUserID {
            get {
                return this.createUserIDField;
            }
            set {
                this.createUserIDField = value;
                this.RaisePropertyChanged("CreateUserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string BeginTime {
            get {
                return this.beginTimeField;
            }
            set {
                this.beginTimeField = value;
                this.RaisePropertyChanged("BeginTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("EndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<int> ConsultDCoopType {
            get {
                return this.consultDCoopTypeField;
            }
            set {
                this.consultDCoopTypeField = value;
                this.RaisePropertyChanged("ConsultDCoopType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string QuestionType {
            get {
                return this.questionTypeField;
            }
            set {
                this.questionTypeField = value;
                this.RaisePropertyChanged("QuestionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string CustName {
            get {
                return this.custNameField;
            }
            set {
                this.custNameField = value;
                this.RaisePropertyChanged("CustName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string IsCompaintStr {
            get {
                return this.isCompaintStrField;
            }
            set {
                this.isCompaintStrField = value;
                this.RaisePropertyChanged("IsCompaintStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string IsIsSendEmailStr {
            get {
                return this.isIsSendEmailStrField;
            }
            set {
                this.isIsSendEmailStrField = value;
                this.RaisePropertyChanged("IsIsSendEmailStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string RightStr {
            get {
                return this.rightStrField;
            }
            set {
                this.rightStrField = value;
                this.RaisePropertyChanged("RightStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string ConsultIDStr {
            get {
                return this.consultIDStrField;
            }
            set {
                this.consultIDStrField = value;
                this.RaisePropertyChanged("ConsultIDStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string QuestionQualityStr {
            get {
                return this.questionQualityStrField;
            }
            set {
                this.questionQualityStrField = value;
                this.RaisePropertyChanged("QuestionQualityStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string IsForwardingStr {
            get {
                return this.isForwardingStrField;
            }
            set {
                this.isForwardingStrField = value;
                this.RaisePropertyChanged("IsForwardingStr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CallRecord_ORIGCondition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int bGIDField;
        
        private int sCIDField;
        
        private string businessIDField;
        
        private string startTimeField;
        
        private string endTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int BGID {
            get {
                return this.bGIDField;
            }
            set {
                this.bGIDField = value;
                this.RaisePropertyChanged("BGID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SCID {
            get {
                return this.sCIDField;
            }
            set {
                this.sCIDField = value;
                this.RaisePropertyChanged("SCID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BusinessID {
            get {
                return this.businessIDField;
            }
            set {
                this.businessIDField = value;
                this.RaisePropertyChanged("BusinessID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("StartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("EndTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CallRecord_ORIG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> transferOutTimeField;
        
        private System.Nullable<System.DateTime> transferInTimeField;
        
        private long recIDField;
        
        private string sessionIDField;
        
        private System.Nullable<long> callIDField;
        
        private System.Nullable<int> siemensCallIDField;
        
        private string genesysCallIDField;
        
        private string extensionNumField;
        
        private string phoneNumField;
        
        private string aNIField;
        
        private System.Nullable<int> callStatusField;
        
        private string switchINNumField;
        
        private System.Nullable<int> outBoundTypeField;
        
        private string skillGroupField;
        
        private System.Nullable<System.DateTime> initiatedTimeField;
        
        private System.Nullable<System.DateTime> ringingTimeField;
        
        private System.Nullable<System.DateTime> establishedTimeField;
        
        private System.Nullable<System.DateTime> customerReleaseTimeField;
        
        private System.Nullable<System.DateTime> agentReleaseTimeField;
        
        private System.Nullable<System.DateTime> afterWorkBeginTimeField;
        
        private System.Nullable<int> afterWorkTimeField;
        
        private System.Nullable<System.DateTime> consultTimeField;
        
        private System.Nullable<System.DateTime> reconnectCallField;
        
        private System.Nullable<int> tallTimeField;
        
        private string audioURLField;
        
        private System.Nullable<System.DateTime> createTimeField;
        
        private System.Nullable<int> createUserIDField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> TransferOutTime {
            get {
                return this.transferOutTimeField;
            }
            set {
                this.transferOutTimeField = value;
                this.RaisePropertyChanged("TransferOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> TransferInTime {
            get {
                return this.transferInTimeField;
            }
            set {
                this.transferInTimeField = value;
                this.RaisePropertyChanged("TransferInTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long RecID {
            get {
                return this.recIDField;
            }
            set {
                this.recIDField = value;
                this.RaisePropertyChanged("RecID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<long> CallID {
            get {
                return this.callIDField;
            }
            set {
                this.callIDField = value;
                this.RaisePropertyChanged("CallID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> SiemensCallID {
            get {
                return this.siemensCallIDField;
            }
            set {
                this.siemensCallIDField = value;
                this.RaisePropertyChanged("SiemensCallID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string GenesysCallID {
            get {
                return this.genesysCallIDField;
            }
            set {
                this.genesysCallIDField = value;
                this.RaisePropertyChanged("GenesysCallID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ExtensionNum {
            get {
                return this.extensionNumField;
            }
            set {
                this.extensionNumField = value;
                this.RaisePropertyChanged("ExtensionNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PhoneNum {
            get {
                return this.phoneNumField;
            }
            set {
                this.phoneNumField = value;
                this.RaisePropertyChanged("PhoneNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ANI {
            get {
                return this.aNIField;
            }
            set {
                this.aNIField = value;
                this.RaisePropertyChanged("ANI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> CallStatus {
            get {
                return this.callStatusField;
            }
            set {
                this.callStatusField = value;
                this.RaisePropertyChanged("CallStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SwitchINNum {
            get {
                return this.switchINNumField;
            }
            set {
                this.switchINNumField = value;
                this.RaisePropertyChanged("SwitchINNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> OutBoundType {
            get {
                return this.outBoundTypeField;
            }
            set {
                this.outBoundTypeField = value;
                this.RaisePropertyChanged("OutBoundType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SkillGroup {
            get {
                return this.skillGroupField;
            }
            set {
                this.skillGroupField = value;
                this.RaisePropertyChanged("SkillGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<System.DateTime> InitiatedTime {
            get {
                return this.initiatedTimeField;
            }
            set {
                this.initiatedTimeField = value;
                this.RaisePropertyChanged("InitiatedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<System.DateTime> RingingTime {
            get {
                return this.ringingTimeField;
            }
            set {
                this.ringingTimeField = value;
                this.RaisePropertyChanged("RingingTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<System.DateTime> EstablishedTime {
            get {
                return this.establishedTimeField;
            }
            set {
                this.establishedTimeField = value;
                this.RaisePropertyChanged("EstablishedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<System.DateTime> CustomerReleaseTime {
            get {
                return this.customerReleaseTimeField;
            }
            set {
                this.customerReleaseTimeField = value;
                this.RaisePropertyChanged("CustomerReleaseTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<System.DateTime> AgentReleaseTime {
            get {
                return this.agentReleaseTimeField;
            }
            set {
                this.agentReleaseTimeField = value;
                this.RaisePropertyChanged("AgentReleaseTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<System.DateTime> AfterWorkBeginTime {
            get {
                return this.afterWorkBeginTimeField;
            }
            set {
                this.afterWorkBeginTimeField = value;
                this.RaisePropertyChanged("AfterWorkBeginTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<int> AfterWorkTime {
            get {
                return this.afterWorkTimeField;
            }
            set {
                this.afterWorkTimeField = value;
                this.RaisePropertyChanged("AfterWorkTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<System.DateTime> ConsultTime {
            get {
                return this.consultTimeField;
            }
            set {
                this.consultTimeField = value;
                this.RaisePropertyChanged("ConsultTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<System.DateTime> ReconnectCall {
            get {
                return this.reconnectCallField;
            }
            set {
                this.reconnectCallField = value;
                this.RaisePropertyChanged("ReconnectCall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<int> TallTime {
            get {
                return this.tallTimeField;
            }
            set {
                this.tallTimeField = value;
                this.RaisePropertyChanged("TallTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string AudioURL {
            get {
                return this.audioURLField;
            }
            set {
                this.audioURLField = value;
                this.RaisePropertyChanged("AudioURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
                this.RaisePropertyChanged("CreateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public System.Nullable<int> CreateUserID {
            get {
                return this.createUserIDField;
            }
            set {
                this.createUserIDField = value;
                this.RaisePropertyChanged("CreateUserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum CallSourceEnum {
        
        /// <remarks/>
        C00_无,
        
        /// <remarks/>
        C01_呼入,
        
        /// <remarks/>
        C02_呼出,
        
        /// <remarks/>
        C03_IM对话,
        
        /// <remarks/>
        C04_IM留言,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CCDataInterfaceServiceSoapChannel : BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.CCDataInterfaceServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CCDataInterfaceServiceSoapClient : System.ServiceModel.ClientBase<BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.CCDataInterfaceServiceSoap>, BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.CCDataInterfaceServiceSoap {
        
        public CCDataInterfaceServiceSoapClient() {
        }
        
        public CCDataInterfaceServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CCDataInterfaceServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCDataInterfaceServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCDataInterfaceServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetCallDataHuiMC(out int totalCount, string Verifycode, string starttime, string endtime, int currentPage, ref string msg) {
            return base.Channel.GetCallDataHuiMC(out totalCount, Verifycode, starttime, endtime, currentPage, ref msg);
        }
        
        public System.Data.DataTable GetInboundDataHuiMC(out int totalCount, string Verifycode, string starttime, string endtime, int currentPage, ref string msg) {
            return base.Channel.GetInboundDataHuiMC(out totalCount, Verifycode, starttime, endtime, currentPage, ref msg);
        }
        
        public System.Data.DataTable GetWorkOrderInfoHMC(out int totalCount, string Verifycode, BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.QueryWorkOrderInfo query, int currentPage, ref string msg) {
            return base.Channel.GetWorkOrderInfoHMC(out totalCount, Verifycode, query, currentPage, ref msg);
        }
        
        public BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.CallRecord_ORIG GetCallDataByCallIDHuiMC(string Verifycode, long callid, ref string msg) {
            return base.Channel.GetCallDataByCallIDHuiMC(Verifycode, callid, ref msg);
        }
        
        public System.Data.DataTable GetCallData(out int totalCount, string Verifycode, BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.CallRecord_ORIGCondition query, int PageIndex, int PageSize, ref string msg) {
            return base.Channel.GetCallData(out totalCount, Verifycode, query, PageIndex, PageSize, ref msg);
        }
        
        public BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.CallRecord_ORIG GetCallDataByCallID(string Verifycode, long callid, ref string msg) {
            return base.Channel.GetCallDataByCallID(Verifycode, callid, ref msg);
        }
        
        public bool CCDataInterface_InsertCustData(out string CustID, out string msg, string Verifycode, string jsonDataStr) {
            return base.Channel.CCDataInterface_InsertCustData(out CustID, out msg, Verifycode, jsonDataStr);
        }
        
        public System.Data.DataTable CCDataInterface_GetCustHistoryInfo(out int totalCount, string Verifycode, int userid, BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.QueryCustHistoryInfo query, int currentPage, ref string msg) {
            return base.Channel.CCDataInterface_GetCustHistoryInfo(out totalCount, Verifycode, userid, query, currentPage, ref msg);
        }
        
        public string GetEmployeeAgentInfo(string Verifycode, int userid) {
            return base.Channel.GetEmployeeAgentInfo(Verifycode, userid);
        }
        
        public string GetCustBasicInfo(string Verifycode, string tel, string name) {
            return base.Channel.GetCustBasicInfo(Verifycode, tel, name);
        }
        
        public string GetAddWOrderComeIn_IMGR_URL(string Verifycode, BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.CallSourceEnum callsource, string phone, long csid, string cbname, int cbsex, int province, int city, int county, int businesstype, int businesstag) {
            return base.Channel.GetAddWOrderComeIn_IMGR_URL(Verifycode, callsource, phone, csid, cbname, cbsex, province, city, county, businesstype, businesstag);
        }
        
        public string GetAddWOrderComeIn_IMJXS_NC_URL(string Verifycode, BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.CallSourceEnum callsource, string phone, long csid, string cbname, int cbsex, int province, int city, int county, string membercode) {
            return base.Channel.GetAddWOrderComeIn_IMJXS_NC_URL(Verifycode, callsource, phone, csid, cbname, cbsex, province, city, county, membercode);
        }
        
        public string GetAddWOrderComeIn_IMJXS_SC_URL(string Verifycode, BitAuto.DSC.IM_2015.WebService.CCDataInterfaceService.CallSourceEnum callsource, string phone, long csid, string cbname, int cbsex, int province, int city, int county, string membercode) {
            return base.Channel.GetAddWOrderComeIn_IMJXS_SC_URL(Verifycode, callsource, phone, csid, cbname, cbsex, province, city, county, membercode);
        }
    }
}
