//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitAuto.ISDC.CC2012.Web.YPSuperLoginService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OauthAccessTokenEntity", Namespace="http://schemas.datacontract.org/2004/07/BitAuto.Beyond.Easy.DAS.Entity")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BitAuto.ISDC.CC2012.Web.YPSuperLoginService.OauthAccessToken))]
    public partial class OauthAccessTokenEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid m_AccessTokenField;
        
        private System.Guid m_AppIdField;
        
        private System.Guid m_AuthorizationCodeField;
        
        private System.Guid m_ClientIDField;
        
        private string m_ClientSecretField;
        
        private System.DateTime m_CreateTimeField;
        
        private int m_DasAccountIDField;
        
        private int m_ExpiresInField;
        
        private string m_GrantTypeField;
        
        private short m_IsActiveField;
        
        private short m_LoginTypeField;
        
        private string m_RedirectUriField;
        
        private System.Guid m_RefreshTokenField;
        
        private string m_ScopeField;
        
        private System.DateTime m_UpdateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid m_AccessToken {
            get {
                return this.m_AccessTokenField;
            }
            set {
                if ((this.m_AccessTokenField.Equals(value) != true)) {
                    this.m_AccessTokenField = value;
                    this.RaisePropertyChanged("m_AccessToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid m_AppId {
            get {
                return this.m_AppIdField;
            }
            set {
                if ((this.m_AppIdField.Equals(value) != true)) {
                    this.m_AppIdField = value;
                    this.RaisePropertyChanged("m_AppId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid m_AuthorizationCode {
            get {
                return this.m_AuthorizationCodeField;
            }
            set {
                if ((this.m_AuthorizationCodeField.Equals(value) != true)) {
                    this.m_AuthorizationCodeField = value;
                    this.RaisePropertyChanged("m_AuthorizationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid m_ClientID {
            get {
                return this.m_ClientIDField;
            }
            set {
                if ((this.m_ClientIDField.Equals(value) != true)) {
                    this.m_ClientIDField = value;
                    this.RaisePropertyChanged("m_ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_ClientSecret {
            get {
                return this.m_ClientSecretField;
            }
            set {
                if ((object.ReferenceEquals(this.m_ClientSecretField, value) != true)) {
                    this.m_ClientSecretField = value;
                    this.RaisePropertyChanged("m_ClientSecret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime m_CreateTime {
            get {
                return this.m_CreateTimeField;
            }
            set {
                if ((this.m_CreateTimeField.Equals(value) != true)) {
                    this.m_CreateTimeField = value;
                    this.RaisePropertyChanged("m_CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int m_DasAccountID {
            get {
                return this.m_DasAccountIDField;
            }
            set {
                if ((this.m_DasAccountIDField.Equals(value) != true)) {
                    this.m_DasAccountIDField = value;
                    this.RaisePropertyChanged("m_DasAccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int m_ExpiresIn {
            get {
                return this.m_ExpiresInField;
            }
            set {
                if ((this.m_ExpiresInField.Equals(value) != true)) {
                    this.m_ExpiresInField = value;
                    this.RaisePropertyChanged("m_ExpiresIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_GrantType {
            get {
                return this.m_GrantTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.m_GrantTypeField, value) != true)) {
                    this.m_GrantTypeField = value;
                    this.RaisePropertyChanged("m_GrantType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short m_IsActive {
            get {
                return this.m_IsActiveField;
            }
            set {
                if ((this.m_IsActiveField.Equals(value) != true)) {
                    this.m_IsActiveField = value;
                    this.RaisePropertyChanged("m_IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short m_LoginType {
            get {
                return this.m_LoginTypeField;
            }
            set {
                if ((this.m_LoginTypeField.Equals(value) != true)) {
                    this.m_LoginTypeField = value;
                    this.RaisePropertyChanged("m_LoginType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_RedirectUri {
            get {
                return this.m_RedirectUriField;
            }
            set {
                if ((object.ReferenceEquals(this.m_RedirectUriField, value) != true)) {
                    this.m_RedirectUriField = value;
                    this.RaisePropertyChanged("m_RedirectUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid m_RefreshToken {
            get {
                return this.m_RefreshTokenField;
            }
            set {
                if ((this.m_RefreshTokenField.Equals(value) != true)) {
                    this.m_RefreshTokenField = value;
                    this.RaisePropertyChanged("m_RefreshToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_Scope {
            get {
                return this.m_ScopeField;
            }
            set {
                if ((object.ReferenceEquals(this.m_ScopeField, value) != true)) {
                    this.m_ScopeField = value;
                    this.RaisePropertyChanged("m_Scope");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime m_UpdateTime {
            get {
                return this.m_UpdateTimeField;
            }
            set {
                if ((this.m_UpdateTimeField.Equals(value) != true)) {
                    this.m_UpdateTimeField = value;
                    this.RaisePropertyChanged("m_UpdateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OauthAccessToken", Namespace="http://schemas.datacontract.org/2004/07/BitAuto.EP.DAS.BLL.Model")]
    [System.SerializableAttribute()]
    public partial class OauthAccessToken : BitAuto.ISDC.CC2012.Web.YPSuperLoginService.OauthAccessTokenEntity {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="YPSuperLoginService.ISuperLoginService")]
    public interface ISuperLoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperLoginService/GetAccessToken", ReplyAction="http://tempuri.org/ISuperLoginService/GetAccessTokenResponse")]
        BitAuto.ISDC.CC2012.Web.YPSuperLoginService.OauthAccessToken GetAccessToken(int DasAccountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperLoginService/GetAccessTokenInType", ReplyAction="http://tempuri.org/ISuperLoginService/GetAccessTokenInTypeResponse")]
        BitAuto.ISDC.CC2012.Web.YPSuperLoginService.OauthAccessToken GetAccessTokenInType(int DasAccountId, short type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperLoginService/GetAccessTokenInTypeByDealerId", ReplyAction="http://tempuri.org/ISuperLoginService/GetAccessTokenInTypeByDealerIdResponse")]
        BitAuto.ISDC.CC2012.Web.YPSuperLoginService.OauthAccessToken GetAccessTokenInTypeByDealerId(int DealerId, short type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISuperLoginServiceChannel : global::BitAuto.ISDC.CC2012.Web.YPSuperLoginService.ISuperLoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SuperLoginServiceClient : System.ServiceModel.ClientBase<global::BitAuto.ISDC.CC2012.Web.YPSuperLoginService.ISuperLoginService>, global::BitAuto.ISDC.CC2012.Web.YPSuperLoginService.ISuperLoginService {
        
        public SuperLoginServiceClient() {
        }
        
        public SuperLoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SuperLoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuperLoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuperLoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BitAuto.ISDC.CC2012.Web.YPSuperLoginService.OauthAccessToken GetAccessToken(int DasAccountId) {
            return base.Channel.GetAccessToken(DasAccountId);
        }
        
        public BitAuto.ISDC.CC2012.Web.YPSuperLoginService.OauthAccessToken GetAccessTokenInType(int DasAccountId, short type) {
            return base.Channel.GetAccessTokenInType(DasAccountId, type);
        }
        
        public BitAuto.ISDC.CC2012.Web.YPSuperLoginService.OauthAccessToken GetAccessTokenInTypeByDealerId(int DealerId, short type) {
            return base.Channel.GetAccessTokenInTypeByDealerId(DealerId, type);
        }
    }
}
