//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1008 版自动生成。
// 
#pragma warning disable 1591

namespace BitAuto.ISDC.CC2012.Web.CRMCytMemberService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CYTMemberSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DictionaryEntry[]))]
    public partial class CYTMember : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetServiceByCstIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberTypeByMemCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CYTMember() {
            this.Url = global::BitAuto.ISDC.CC2012.Web.Properties.Settings.Default.BitAuto_ISDC_CC2012_Web_CRMCytMemberService_CYTMember;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetServiceByCstIDCompletedEventHandler GetServiceByCstIDCompleted;
        
        /// <remarks/>
        public event GetMemberTypeByMemCodeCompletedEventHandler GetMemberTypeByMemCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetServiceByCstID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetServiceByCstID(int CstID) {
            object[] results = this.Invoke("GetServiceByCstID", new object[] {
                        CstID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetServiceByCstIDAsync(int CstID) {
            this.GetServiceByCstIDAsync(CstID, null);
        }
        
        /// <remarks/>
        public void GetServiceByCstIDAsync(int CstID, object userState) {
            if ((this.GetServiceByCstIDOperationCompleted == null)) {
                this.GetServiceByCstIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceByCstIDOperationCompleted);
            }
            this.InvokeAsync("GetServiceByCstID", new object[] {
                        CstID}, this.GetServiceByCstIDOperationCompleted, userState);
        }
        
        private void OnGetServiceByCstIDOperationCompleted(object arg) {
            if ((this.GetServiceByCstIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiceByCstIDCompleted(this, new GetServiceByCstIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberTypeByMemCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DictionaryEntry[] GetMemberTypeByMemCode(string[] arrMember) {
            object[] results = this.Invoke("GetMemberTypeByMemCode", new object[] {
                        arrMember});
            return ((DictionaryEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberTypeByMemCodeAsync(string[] arrMember) {
            this.GetMemberTypeByMemCodeAsync(arrMember, null);
        }
        
        /// <remarks/>
        public void GetMemberTypeByMemCodeAsync(string[] arrMember, object userState) {
            if ((this.GetMemberTypeByMemCodeOperationCompleted == null)) {
                this.GetMemberTypeByMemCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberTypeByMemCodeOperationCompleted);
            }
            this.InvokeAsync("GetMemberTypeByMemCode", new object[] {
                        arrMember}, this.GetMemberTypeByMemCodeOperationCompleted, userState);
        }
        
        private void OnGetMemberTypeByMemCodeOperationCompleted(object arg) {
            if ((this.GetMemberTypeByMemCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberTypeByMemCodeCompleted(this, new GetMemberTypeByMemCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DictionaryEntry {
        
        private object keyField;
        
        private object valueField;
        
        /// <remarks/>
        public object Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetServiceByCstIDCompletedEventHandler(object sender, GetServiceByCstIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiceByCstIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiceByCstIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMemberTypeByMemCodeCompletedEventHandler(object sender, GetMemberTypeByMemCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberTypeByMemCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberTypeByMemCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DictionaryEntry[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DictionaryEntry[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591