//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1026 版自动生成。
// 
#pragma warning disable 1591

namespace BitAuto.ISDC.CC2012.WebService.CRM.CustomerService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerServiceSoap", Namespace="http://crm.bitauto.com/dms/")]
    public partial class CustomerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMappingOfCustAndDealerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDealerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberUserByMemberCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberContactByMemberCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateContactEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetJiCaiOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCityManagerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAreaInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncUserBrandOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncMemberBrandOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDistrictManagerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CustomerService() {
            this.Url = global::BitAuto.ISDC.CC2012.WebService.Properties.Settings.Default.BitAuto_ISDC_CC2012_WebService_CRM_CustomerService_CustomerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMappingOfCustAndDealerCompletedEventHandler GetMappingOfCustAndDealerCompleted;
        
        /// <remarks/>
        public event GetDealerInfoCompletedEventHandler GetDealerInfoCompleted;
        
        /// <remarks/>
        public event GetMemberUserByMemberCodeCompletedEventHandler GetMemberUserByMemberCodeCompleted;
        
        /// <remarks/>
        public event GetMemberUserCompletedEventHandler GetMemberUserCompleted;
        
        /// <remarks/>
        public event GetMemberContactByMemberCodeCompletedEventHandler GetMemberContactByMemberCodeCompleted;
        
        /// <remarks/>
        public event UpdateContactEmailCompletedEventHandler UpdateContactEmailCompleted;
        
        /// <remarks/>
        public event GetOrderUserInfoCompletedEventHandler GetOrderUserInfoCompleted;
        
        /// <remarks/>
        public event GetJiCaiOrderCompletedEventHandler GetJiCaiOrderCompleted;
        
        /// <remarks/>
        public event GetCityManagerCompletedEventHandler GetCityManagerCompleted;
        
        /// <remarks/>
        public event GetAreaInfoCompletedEventHandler GetAreaInfoCompleted;
        
        /// <remarks/>
        public event SyncUserBrandCompletedEventHandler SyncUserBrandCompleted;
        
        /// <remarks/>
        public event SyncMemberBrandCompletedEventHandler SyncMemberBrandCompleted;
        
        /// <remarks/>
        public event GetDistrictManagerCompletedEventHandler GetDistrictManagerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crm.bitauto.com/dms/GetMappingOfCustAndDealer", RequestNamespace="http://crm.bitauto.com/dms/", ResponseNamespace="http://crm.bitauto.com/dms/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMappingOfCustAndDealer() {
            object[] results = this.Invoke("GetMappingOfCustAndDealer", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetMappingOfCustAndDealerAsync() {
            this.GetMappingOfCustAndDealerAsync(null);
        }
        
        /// <remarks/>
        public void GetMappingOfCustAndDealerAsync(object userState) {
            if ((this.GetMappingOfCustAndDealerOperationCompleted == null)) {
                this.GetMappingOfCustAndDealerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMappingOfCustAndDealerOperationCompleted);
            }
            this.InvokeAsync("GetMappingOfCustAndDealer", new object[0], this.GetMappingOfCustAndDealerOperationCompleted, userState);
        }
        
        private void OnGetMappingOfCustAndDealerOperationCompleted(object arg) {
            if ((this.GetMappingOfCustAndDealerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMappingOfCustAndDealerCompleted(this, new GetMappingOfCustAndDealerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crm.bitauto.com/dms/GetDealerInfo", RequestNamespace="http://crm.bitauto.com/dms/", ResponseNamespace="http://crm.bitauto.com/dms/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetDealerInfo(System.DateTime lastTime) {
            object[] results = this.Invoke("GetDealerInfo", new object[] {
                        lastTime});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetDealerInfoAsync(System.DateTime lastTime) {
            this.GetDealerInfoAsync(lastTime, null);
        }
        
        /// <remarks/>
        public void GetDealerInfoAsync(System.DateTime lastTime, object userState) {
            if ((this.GetDealerInfoOperationCompleted == null)) {
                this.GetDealerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDealerInfoOperationCompleted);
            }
            this.InvokeAsync("GetDealerInfo", new object[] {
                        lastTime}, this.GetDealerInfoOperationCompleted, userState);
        }
        
        private void OnGetDealerInfoOperationCompleted(object arg) {
            if ((this.GetDealerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDealerInfoCompleted(this, new GetDealerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crm.bitauto.com/dms/GetMemberUserByMemberCode", RequestNamespace="http://crm.bitauto.com/dms/", ResponseNamespace="http://crm.bitauto.com/dms/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMemberUserByMemberCode(string memberCode) {
            object[] results = this.Invoke("GetMemberUserByMemberCode", new object[] {
                        memberCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberUserByMemberCodeAsync(string memberCode) {
            this.GetMemberUserByMemberCodeAsync(memberCode, null);
        }
        
        /// <remarks/>
        public void GetMemberUserByMemberCodeAsync(string memberCode, object userState) {
            if ((this.GetMemberUserByMemberCodeOperationCompleted == null)) {
                this.GetMemberUserByMemberCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberUserByMemberCodeOperationCompleted);
            }
            this.InvokeAsync("GetMemberUserByMemberCode", new object[] {
                        memberCode}, this.GetMemberUserByMemberCodeOperationCompleted, userState);
        }
        
        private void OnGetMemberUserByMemberCodeOperationCompleted(object arg) {
            if ((this.GetMemberUserByMemberCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberUserByMemberCodeCompleted(this, new GetMemberUserByMemberCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crm.bitauto.com/dms/GetMemberUser", RequestNamespace="http://crm.bitauto.com/dms/", ResponseNamespace="http://crm.bitauto.com/dms/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMemberUser(string key, System.DateTime modifyTime) {
            object[] results = this.Invoke("GetMemberUser", new object[] {
                        key,
                        modifyTime});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberUserAsync(string key, System.DateTime modifyTime) {
            this.GetMemberUserAsync(key, modifyTime, null);
        }
        
        /// <remarks/>
        public void GetMemberUserAsync(string key, System.DateTime modifyTime, object userState) {
            if ((this.GetMemberUserOperationCompleted == null)) {
                this.GetMemberUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberUserOperationCompleted);
            }
            this.InvokeAsync("GetMemberUser", new object[] {
                        key,
                        modifyTime}, this.GetMemberUserOperationCompleted, userState);
        }
        
        private void OnGetMemberUserOperationCompleted(object arg) {
            if ((this.GetMemberUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberUserCompleted(this, new GetMemberUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crm.bitauto.com/dms/GetMemberContactByMemberCode", RequestNamespace="http://crm.bitauto.com/dms/", ResponseNamespace="http://crm.bitauto.com/dms/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMemberContactByMemberCode(string membercode) {
            object[] results = this.Invoke("GetMemberContactByMemberCode", new object[] {
                        membercode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberContactByMemberCodeAsync(string membercode) {
            this.GetMemberContactByMemberCodeAsync(membercode, null);
        }
        
        /// <remarks/>
        public void GetMemberContactByMemberCodeAsync(string membercode, object userState) {
            if ((this.GetMemberContactByMemberCodeOperationCompleted == null)) {
                this.GetMemberContactByMemberCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberContactByMemberCodeOperationCompleted);
            }
            this.InvokeAsync("GetMemberContactByMemberCode", new object[] {
                        membercode}, this.GetMemberContactByMemberCodeOperationCompleted, userState);
        }
        
        private void OnGetMemberContactByMemberCodeOperationCompleted(object arg) {
            if ((this.GetMemberContactByMemberCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberContactByMemberCodeCompleted(this, new GetMemberContactByMemberCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crm.bitauto.com/dms/UpdateContactEmail", RequestNamespace="http://crm.bitauto.com/dms/", ResponseNamespace="http://crm.bitauto.com/dms/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateContactEmail(int contactID, string email, out string msg) {
            object[] results = this.Invoke("UpdateContactEmail", new object[] {
                        contactID,
                        email});
            msg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateContactEmailAsync(int contactID, string email) {
            this.UpdateContactEmailAsync(contactID, email, null);
        }
        
        /// <remarks/>
        public void UpdateContactEmailAsync(int contactID, string email, object userState) {
            if ((this.UpdateContactEmailOperationCompleted == null)) {
                this.UpdateContactEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateContactEmailOperationCompleted);
            }
            this.InvokeAsync("UpdateContactEmail", new object[] {
                        contactID,
                        email}, this.UpdateContactEmailOperationCompleted, userState);
        }
        
        private void OnUpdateContactEmailOperationCompleted(object arg) {
            if ((this.UpdateContactEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateContactEmailCompleted(this, new UpdateContactEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crm.bitauto.com/dms/GetOrderUserInfo", RequestNamespace="http://crm.bitauto.com/dms/", ResponseNamespace="http://crm.bitauto.com/dms/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetOrderUserInfo(string orderCode) {
            object[] results = this.Invoke("GetOrderUserInfo", new object[] {
                        orderCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderUserInfoAsync(string orderCode) {
            this.GetOrderUserInfoAsync(orderCode, null);
        }
        
        /// <remarks/>
        public void GetOrderUserInfoAsync(string orderCode, object userState) {
            if ((this.GetOrderUserInfoOperationCompleted == null)) {
                this.GetOrderUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderUserInfoOperationCompleted);
            }
            this.InvokeAsync("GetOrderUserInfo", new object[] {
                        orderCode}, this.GetOrderUserInfoOperationCompleted, userState);
        }
        
        private void OnGetOrderUserInfoOperationCompleted(object arg) {
            if ((this.GetOrderUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderUserInfoCompleted(this, new GetOrderUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crm.bitauto.com/dms/GetJiCaiOrder", RequestNamespace="http://crm.bitauto.com/dms/", ResponseNamespace="http://crm.bitauto.com/dms/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetJiCaiOrder() {
            object[] results = this.Invoke("GetJiCaiOrder", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetJiCaiOrderAsync() {
            this.GetJiCaiOrderAsync(null);
        }
        
        /// <remarks/>
        public void GetJiCaiOrderAsync(object userState) {
            if ((this.GetJiCaiOrderOperationCompleted == null)) {
                this.GetJiCaiOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetJiCaiOrderOperationCompleted);
            }
            this.InvokeAsync("GetJiCaiOrder", new object[0], this.GetJiCaiOrderOperationCompleted, userState);
        }
        
        private void OnGetJiCaiOrderOperationCompleted(object arg) {
            if ((this.GetJiCaiOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetJiCaiOrderCompleted(this, new GetJiCaiOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crm.bitauto.com/dms/GetCityManager", RequestNamespace="http://crm.bitauto.com/dms/", ResponseNamespace="http://crm.bitauto.com/dms/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCityManager() {
            object[] results = this.Invoke("GetCityManager", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCityManagerAsync() {
            this.GetCityManagerAsync(null);
        }
        
        /// <remarks/>
        public void GetCityManagerAsync(object userState) {
            if ((this.GetCityManagerOperationCompleted == null)) {
                this.GetCityManagerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCityManagerOperationCompleted);
            }
            this.InvokeAsync("GetCityManager", new object[0], this.GetCityManagerOperationCompleted, userState);
        }
        
        private void OnGetCityManagerOperationCompleted(object arg) {
            if ((this.GetCityManagerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCityManagerCompleted(this, new GetCityManagerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crm.bitauto.com/dms/GetAreaInfo", RequestNamespace="http://crm.bitauto.com/dms/", ResponseNamespace="http://crm.bitauto.com/dms/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAreaInfo() {
            object[] results = this.Invoke("GetAreaInfo", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAreaInfoAsync() {
            this.GetAreaInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetAreaInfoAsync(object userState) {
            if ((this.GetAreaInfoOperationCompleted == null)) {
                this.GetAreaInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAreaInfoOperationCompleted);
            }
            this.InvokeAsync("GetAreaInfo", new object[0], this.GetAreaInfoOperationCompleted, userState);
        }
        
        private void OnGetAreaInfoOperationCompleted(object arg) {
            if ((this.GetAreaInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAreaInfoCompleted(this, new GetAreaInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crm.bitauto.com/dms/SyncUserBrand", RequestNamespace="http://crm.bitauto.com/dms/", ResponseNamespace="http://crm.bitauto.com/dms/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SyncUserBrand() {
            object[] results = this.Invoke("SyncUserBrand", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SyncUserBrandAsync() {
            this.SyncUserBrandAsync(null);
        }
        
        /// <remarks/>
        public void SyncUserBrandAsync(object userState) {
            if ((this.SyncUserBrandOperationCompleted == null)) {
                this.SyncUserBrandOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncUserBrandOperationCompleted);
            }
            this.InvokeAsync("SyncUserBrand", new object[0], this.SyncUserBrandOperationCompleted, userState);
        }
        
        private void OnSyncUserBrandOperationCompleted(object arg) {
            if ((this.SyncUserBrandCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncUserBrandCompleted(this, new SyncUserBrandCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crm.bitauto.com/dms/SyncMemberBrand", RequestNamespace="http://crm.bitauto.com/dms/", ResponseNamespace="http://crm.bitauto.com/dms/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SyncMemberBrand(System.DateTime modifyTime) {
            object[] results = this.Invoke("SyncMemberBrand", new object[] {
                        modifyTime});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SyncMemberBrandAsync(System.DateTime modifyTime) {
            this.SyncMemberBrandAsync(modifyTime, null);
        }
        
        /// <remarks/>
        public void SyncMemberBrandAsync(System.DateTime modifyTime, object userState) {
            if ((this.SyncMemberBrandOperationCompleted == null)) {
                this.SyncMemberBrandOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncMemberBrandOperationCompleted);
            }
            this.InvokeAsync("SyncMemberBrand", new object[] {
                        modifyTime}, this.SyncMemberBrandOperationCompleted, userState);
        }
        
        private void OnSyncMemberBrandOperationCompleted(object arg) {
            if ((this.SyncMemberBrandCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncMemberBrandCompleted(this, new SyncMemberBrandCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://crm.bitauto.com/dms/GetDistrictManager", RequestNamespace="http://crm.bitauto.com/dms/", ResponseNamespace="http://crm.bitauto.com/dms/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetDistrictManager() {
            object[] results = this.Invoke("GetDistrictManager", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetDistrictManagerAsync() {
            this.GetDistrictManagerAsync(null);
        }
        
        /// <remarks/>
        public void GetDistrictManagerAsync(object userState) {
            if ((this.GetDistrictManagerOperationCompleted == null)) {
                this.GetDistrictManagerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDistrictManagerOperationCompleted);
            }
            this.InvokeAsync("GetDistrictManager", new object[0], this.GetDistrictManagerOperationCompleted, userState);
        }
        
        private void OnGetDistrictManagerOperationCompleted(object arg) {
            if ((this.GetDistrictManagerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDistrictManagerCompleted(this, new GetDistrictManagerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMappingOfCustAndDealerCompletedEventHandler(object sender, GetMappingOfCustAndDealerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMappingOfCustAndDealerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMappingOfCustAndDealerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDealerInfoCompletedEventHandler(object sender, GetDealerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDealerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDealerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMemberUserByMemberCodeCompletedEventHandler(object sender, GetMemberUserByMemberCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberUserByMemberCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberUserByMemberCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMemberUserCompletedEventHandler(object sender, GetMemberUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMemberContactByMemberCodeCompletedEventHandler(object sender, GetMemberContactByMemberCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberContactByMemberCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberContactByMemberCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateContactEmailCompletedEventHandler(object sender, UpdateContactEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateContactEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateContactEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOrderUserInfoCompletedEventHandler(object sender, GetOrderUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetJiCaiOrderCompletedEventHandler(object sender, GetJiCaiOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetJiCaiOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetJiCaiOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCityManagerCompletedEventHandler(object sender, GetCityManagerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCityManagerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCityManagerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAreaInfoCompletedEventHandler(object sender, GetAreaInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAreaInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAreaInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SyncUserBrandCompletedEventHandler(object sender, SyncUserBrandCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncUserBrandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncUserBrandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SyncMemberBrandCompletedEventHandler(object sender, SyncMemberBrandCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncMemberBrandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncMemberBrandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDistrictManagerCompletedEventHandler(object sender, GetDistrictManagerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDistrictManagerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDistrictManagerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591