//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1026 版自动生成。
// 
#pragma warning disable 1591

namespace BitAuto.ISDC.CC2012.WebService.CC.CallRecordService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetCallRecordListSoap", Namespace="http://tempuri.org/")]
    public partial class GetCallRecordList : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCallRecordByMaxIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateBusinessDataByCallIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAgentRoleNameByDomainAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAgentInfoByConditionOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertCustDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertCustDataReturnStrOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDemandCallDetailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetCallRecordList() {
            this.Url = global::BitAuto.ISDC.CC2012.WebService.Properties.Settings.Default.BitAuto_ISDC_CC2012_WebService_CC_CallRecordService_GetCallRecordList;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCallRecordByMaxIDCompletedEventHandler GetCallRecordByMaxIDCompleted;
        
        /// <remarks/>
        public event UpdateBusinessDataByCallIDCompletedEventHandler UpdateBusinessDataByCallIDCompleted;
        
        /// <remarks/>
        public event GetAgentRoleNameByDomainAccountCompletedEventHandler GetAgentRoleNameByDomainAccountCompleted;
        
        /// <remarks/>
        public event GetAgentInfoByConditionCompletedEventHandler GetAgentInfoByConditionCompleted;
        
        /// <remarks/>
        public event InsertCustDataCompletedEventHandler InsertCustDataCompleted;
        
        /// <remarks/>
        public event InsertCustDataReturnStrCompletedEventHandler InsertCustDataReturnStrCompleted;
        
        /// <remarks/>
        public event GetDemandCallDetailCompletedEventHandler GetDemandCallDetailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCallRecordByMaxID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCallRecordByMaxID(string Verifycode, int maxID, ref string msg) {
            object[] results = this.Invoke("GetCallRecordByMaxID", new object[] {
                        Verifycode,
                        maxID,
                        msg});
            msg = ((string)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCallRecordByMaxIDAsync(string Verifycode, int maxID, string msg) {
            this.GetCallRecordByMaxIDAsync(Verifycode, maxID, msg, null);
        }
        
        /// <remarks/>
        public void GetCallRecordByMaxIDAsync(string Verifycode, int maxID, string msg, object userState) {
            if ((this.GetCallRecordByMaxIDOperationCompleted == null)) {
                this.GetCallRecordByMaxIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCallRecordByMaxIDOperationCompleted);
            }
            this.InvokeAsync("GetCallRecordByMaxID", new object[] {
                        Verifycode,
                        maxID,
                        msg}, this.GetCallRecordByMaxIDOperationCompleted, userState);
        }
        
        private void OnGetCallRecordByMaxIDOperationCompleted(object arg) {
            if ((this.GetCallRecordByMaxIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCallRecordByMaxIDCompleted(this, new GetCallRecordByMaxIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateBusinessDataByCallID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateBusinessDataByCallID(string Verifycode, long callID, string businessID, int BGID, int SCID, int createuserid, ref string msg) {
            object[] results = this.Invoke("UpdateBusinessDataByCallID", new object[] {
                        Verifycode,
                        callID,
                        businessID,
                        BGID,
                        SCID,
                        createuserid,
                        msg});
            msg = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateBusinessDataByCallIDAsync(string Verifycode, long callID, string businessID, int BGID, int SCID, int createuserid, string msg) {
            this.UpdateBusinessDataByCallIDAsync(Verifycode, callID, businessID, BGID, SCID, createuserid, msg, null);
        }
        
        /// <remarks/>
        public void UpdateBusinessDataByCallIDAsync(string Verifycode, long callID, string businessID, int BGID, int SCID, int createuserid, string msg, object userState) {
            if ((this.UpdateBusinessDataByCallIDOperationCompleted == null)) {
                this.UpdateBusinessDataByCallIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateBusinessDataByCallIDOperationCompleted);
            }
            this.InvokeAsync("UpdateBusinessDataByCallID", new object[] {
                        Verifycode,
                        callID,
                        businessID,
                        BGID,
                        SCID,
                        createuserid,
                        msg}, this.UpdateBusinessDataByCallIDOperationCompleted, userState);
        }
        
        private void OnUpdateBusinessDataByCallIDOperationCompleted(object arg) {
            if ((this.UpdateBusinessDataByCallIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateBusinessDataByCallIDCompleted(this, new UpdateBusinessDataByCallIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAgentRoleNameByDomainAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAgentRoleNameByDomainAccount(string Verifycode, string domainAccount) {
            object[] results = this.Invoke("GetAgentRoleNameByDomainAccount", new object[] {
                        Verifycode,
                        domainAccount});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAgentRoleNameByDomainAccountAsync(string Verifycode, string domainAccount) {
            this.GetAgentRoleNameByDomainAccountAsync(Verifycode, domainAccount, null);
        }
        
        /// <remarks/>
        public void GetAgentRoleNameByDomainAccountAsync(string Verifycode, string domainAccount, object userState) {
            if ((this.GetAgentRoleNameByDomainAccountOperationCompleted == null)) {
                this.GetAgentRoleNameByDomainAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAgentRoleNameByDomainAccountOperationCompleted);
            }
            this.InvokeAsync("GetAgentRoleNameByDomainAccount", new object[] {
                        Verifycode,
                        domainAccount}, this.GetAgentRoleNameByDomainAccountOperationCompleted, userState);
        }
        
        private void OnGetAgentRoleNameByDomainAccountOperationCompleted(object arg) {
            if ((this.GetAgentRoleNameByDomainAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAgentRoleNameByDomainAccountCompleted(this, new GetAgentRoleNameByDomainAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAgentInfoByCondition", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAgentInfoByCondition(string Verifycode, AgentInfoCondition AgentInfoCondition, int PageSize, int PageIndex, ref int RecordCount, ref string msg) {
            object[] results = this.Invoke("GetAgentInfoByCondition", new object[] {
                        Verifycode,
                        AgentInfoCondition,
                        PageSize,
                        PageIndex,
                        RecordCount,
                        msg});
            RecordCount = ((int)(results[1]));
            msg = ((string)(results[2]));
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAgentInfoByConditionAsync(string Verifycode, AgentInfoCondition AgentInfoCondition, int PageSize, int PageIndex, int RecordCount, string msg) {
            this.GetAgentInfoByConditionAsync(Verifycode, AgentInfoCondition, PageSize, PageIndex, RecordCount, msg, null);
        }
        
        /// <remarks/>
        public void GetAgentInfoByConditionAsync(string Verifycode, AgentInfoCondition AgentInfoCondition, int PageSize, int PageIndex, int RecordCount, string msg, object userState) {
            if ((this.GetAgentInfoByConditionOperationCompleted == null)) {
                this.GetAgentInfoByConditionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAgentInfoByConditionOperationCompleted);
            }
            this.InvokeAsync("GetAgentInfoByCondition", new object[] {
                        Verifycode,
                        AgentInfoCondition,
                        PageSize,
                        PageIndex,
                        RecordCount,
                        msg}, this.GetAgentInfoByConditionOperationCompleted, userState);
        }
        
        private void OnGetAgentInfoByConditionOperationCompleted(object arg) {
            if ((this.GetAgentInfoByConditionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAgentInfoByConditionCompleted(this, new GetAgentInfoByConditionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertCustData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EnumResult InsertCustData(string Verifycode, string jsonDataStr) {
            object[] results = this.Invoke("InsertCustData", new object[] {
                        Verifycode,
                        jsonDataStr});
            return ((EnumResult)(results[0]));
        }
        
        /// <remarks/>
        public void InsertCustDataAsync(string Verifycode, string jsonDataStr) {
            this.InsertCustDataAsync(Verifycode, jsonDataStr, null);
        }
        
        /// <remarks/>
        public void InsertCustDataAsync(string Verifycode, string jsonDataStr, object userState) {
            if ((this.InsertCustDataOperationCompleted == null)) {
                this.InsertCustDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertCustDataOperationCompleted);
            }
            this.InvokeAsync("InsertCustData", new object[] {
                        Verifycode,
                        jsonDataStr}, this.InsertCustDataOperationCompleted, userState);
        }
        
        private void OnInsertCustDataOperationCompleted(object arg) {
            if ((this.InsertCustDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertCustDataCompleted(this, new InsertCustDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertCustDataReturnStr", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertCustDataReturnStr(string Verifycode, string jsonDataStr) {
            object[] results = this.Invoke("InsertCustDataReturnStr", new object[] {
                        Verifycode,
                        jsonDataStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertCustDataReturnStrAsync(string Verifycode, string jsonDataStr) {
            this.InsertCustDataReturnStrAsync(Verifycode, jsonDataStr, null);
        }
        
        /// <remarks/>
        public void InsertCustDataReturnStrAsync(string Verifycode, string jsonDataStr, object userState) {
            if ((this.InsertCustDataReturnStrOperationCompleted == null)) {
                this.InsertCustDataReturnStrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertCustDataReturnStrOperationCompleted);
            }
            this.InvokeAsync("InsertCustDataReturnStr", new object[] {
                        Verifycode,
                        jsonDataStr}, this.InsertCustDataReturnStrOperationCompleted, userState);
        }
        
        private void OnInsertCustDataReturnStrOperationCompleted(object arg) {
            if ((this.InsertCustDataReturnStrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertCustDataReturnStrCompleted(this, new InsertCustDataReturnStrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDemandCallDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetDemandCallDetail(string Verifycode, CallRecordInfoCondition model, int PageIndex, int PageSize, out int RecordCount, out string Msg) {
            object[] results = this.Invoke("GetDemandCallDetail", new object[] {
                        Verifycode,
                        model,
                        PageIndex,
                        PageSize});
            RecordCount = ((int)(results[1]));
            Msg = ((string)(results[2]));
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetDemandCallDetailAsync(string Verifycode, CallRecordInfoCondition model, int PageIndex, int PageSize) {
            this.GetDemandCallDetailAsync(Verifycode, model, PageIndex, PageSize, null);
        }
        
        /// <remarks/>
        public void GetDemandCallDetailAsync(string Verifycode, CallRecordInfoCondition model, int PageIndex, int PageSize, object userState) {
            if ((this.GetDemandCallDetailOperationCompleted == null)) {
                this.GetDemandCallDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDemandCallDetailOperationCompleted);
            }
            this.InvokeAsync("GetDemandCallDetail", new object[] {
                        Verifycode,
                        model,
                        PageIndex,
                        PageSize}, this.GetDemandCallDetailOperationCompleted, userState);
        }
        
        private void OnGetDemandCallDetailOperationCompleted(object arg) {
            if ((this.GetDemandCallDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDemandCallDetailCompleted(this, new GetDemandCallDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AgentInfoCondition {
        
        private int userIDField;
        
        private int loginUserIDField;
        
        private int bGIDField;
        
        private string trueNameField;
        
        private string aDNameField;
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public int LoginUserID {
            get {
                return this.loginUserIDField;
            }
            set {
                this.loginUserIDField = value;
            }
        }
        
        /// <remarks/>
        public int BGID {
            get {
                return this.bGIDField;
            }
            set {
                this.bGIDField = value;
            }
        }
        
        /// <remarks/>
        public string TrueName {
            get {
                return this.trueNameField;
            }
            set {
                this.trueNameField = value;
            }
        }
        
        /// <remarks/>
        public string ADName {
            get {
                return this.aDNameField;
            }
            set {
                this.aDNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CallRecordInfoCondition {
        
        private int bGIDField;
        
        private int sCIDField;
        
        private string businessIDField;
        
        /// <remarks/>
        public int BGID {
            get {
                return this.bGIDField;
            }
            set {
                this.bGIDField = value;
            }
        }
        
        /// <remarks/>
        public int SCID {
            get {
                return this.sCIDField;
            }
            set {
                this.sCIDField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessID {
            get {
                return this.businessIDField;
            }
            set {
                this.businessIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EnumResult {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        VerifyError,
        
        /// <remarks/>
        JsonPatternError,
        
        /// <remarks/>
        CustNameEmpty,
        
        /// <remarks/>
        SexPatternError,
        
        /// <remarks/>
        CustTelEmpty,
        
        /// <remarks/>
        CustTelPatternError,
        
        /// <remarks/>
        CallIDEmpty,
        
        /// <remarks/>
        CallIDPatternError,
        
        /// <remarks/>
        CallIDNotExist,
        
        /// <remarks/>
        BusinessIDEmpty,
        
        /// <remarks/>
        BGIDEmpty,
        
        /// <remarks/>
        BGIDPatternError,
        
        /// <remarks/>
        SCIDEmpty,
        
        /// <remarks/>
        SCIDPatternError,
        
        /// <remarks/>
        MemberCodeError,
        
        /// <remarks/>
        Fail,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCallRecordByMaxIDCompletedEventHandler(object sender, GetCallRecordByMaxIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCallRecordByMaxIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCallRecordByMaxIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateBusinessDataByCallIDCompletedEventHandler(object sender, UpdateBusinessDataByCallIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateBusinessDataByCallIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateBusinessDataByCallIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAgentRoleNameByDomainAccountCompletedEventHandler(object sender, GetAgentRoleNameByDomainAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAgentRoleNameByDomainAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAgentRoleNameByDomainAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAgentInfoByConditionCompletedEventHandler(object sender, GetAgentInfoByConditionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAgentInfoByConditionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAgentInfoByConditionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int RecordCount {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InsertCustDataCompletedEventHandler(object sender, InsertCustDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertCustDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertCustDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EnumResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EnumResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InsertCustDataReturnStrCompletedEventHandler(object sender, InsertCustDataReturnStrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertCustDataReturnStrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertCustDataReturnStrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDemandCallDetailCompletedEventHandler(object sender, GetDemandCallDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDemandCallDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDemandCallDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int RecordCount {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string Msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591