//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitAuto.ISDC.CC2012.WebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://test1.api.dealer.bitauto.com/api/InnerService/ActiveOrder_Crm.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_YpGroupOrderService_ActiveOrder_Crm {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_YpGroupOrderService_ActiveOrder_Crm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.market.bitauto.com/GetData/Recommend.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_MarketService_Recommend {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_MarketService_Recommend"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ncc.sys1.bitauto.com/WebServices/YTGActivityService.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_YTGActivityService_YTGActivityService {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_YTGActivityService_YTGActivityService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ncc.sys1.bitauto.com/WebServices/DictionaryDataCacheService.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_DictionaryDataCacheService_DictionaryDataCacheService {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_DictionaryDataCacheService_DictionaryDataCacheServ" +
                    "ice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://crm.sys1.bitauto.com/DMS/CustCoorperation.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_CRM_CooperationServicce_CustCoorperation {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_CRM_CooperationServicce_CustCoorperation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://crm.sys1.bitauto.com/DMS/CustomerService.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_CRM_CustomerService_CustomerService {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_CRM_CustomerService_CustomerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ncc.sys1.bitauto.com/CallRecordService/GetCallRecordList.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_CC_CallRecordService_GetCallRecordList {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_CC_CallRecordService_GetCallRecordList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.baa.bitauto.com/ibt/AuthenWebService.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_BAA_QiCheTongService_AuthenWebService {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_BAA_QiCheTongService_AuthenWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.baa.bitauto.com/ibt/UserManagerWebService.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_BAA_QiCheTongQueryService_UserManagerWebService {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_BAA_QiCheTongQueryService_UserManagerWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.baa.bitauto.com/UGCSync/UGCSyncService.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_BAA_UGCSyncService_UGCSyncService {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_BAA_UGCSyncService_UGCSyncService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.ucar.cn/Dealer/TranstarToBitautoCRM.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_TaoChe_CstMemberService_TranstarToBitautoCRM {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_TaoChe_CstMemberService_TranstarToBitautoCRM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mobile.bitauto.com/smsplatform/interface/MsgService.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_ITSupport_SMSService_MsgService {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_ITSupport_SMSService_MsgService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://easyop.bitauto.com/DMS/OuterService/DealerInfoService.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_EasyPass_DealerInfoService_DealerInfoService {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_EasyPass_DealerInfoService_DealerInfoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api2.easypass.cn/das/inner/UserGetPwd.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_EasyPass_RestPwdService_UserGetPwd {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_EasyPass_RestPwdService_UserGetPwd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://test1.partner.bitauto.com/api/order/withoutdealerorderservice.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_EasyPass_WithoutDealerOrderService_WithoutDealerOrderService {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_EasyPass_WithoutDealerOrderService_WithoutDealerOr" +
                    "derService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sys1.bitauto.com/service/userinfo.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_CRM_UserInfoService_RightsService {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_CRM_UserInfoService_RightsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://imep.sys1.bitauto.com/WebService/Utils.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_IMep_UtilsService_Utils {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_IMep_UtilsService_Utils"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://imtc.sys1.bitauto.com/WebService/Utils.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_IMtc_UtilsService_Utils {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_IMtc_UtilsService_Utils"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://im.sys1.bitauto.com/WebService/Utils.asmx")]
        public string BitAuto_ISDC_CC2012_WebService_IM_UtilsService_Utils {
            get {
                return ((string)(this["BitAuto_ISDC_CC2012_WebService_IM_UtilsService_Utils"]));
            }
        }
    }
}
