//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitAuto.ISDC.CC2012.WebService.GetAgentInfo.ServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetAgentInfo.ServiceReference.GetCallRecordListSoap")]
    public interface GetCallRecordListSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCallRecordByMaxID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCallRecordByMaxID(string Verifycode, int maxID, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBusinessDataByCallID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateBusinessDataByCallID(string Verifycode, long callID, string businessID, int BGID, int SCID, int createuserid, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAgentInfoByBGID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAgentInfoByBGID(string Verifycode, int LoginUserID, string TrueName, int PageSize, int PageIndex, ref int RecordCount, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAgentRoleNameByDomainAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAgentRoleNameByDomainAccount(string Verifycode, string domainAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAgentInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAgentInfo(string Verifycode, int UserID, string ADName, ref int RecordCount, ref string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAgentInfoByCondition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAgentInfoByCondition(string Verifycode, BitAuto.ISDC.CC2012.WebService.GetAgentInfo.ServiceReference.AgentInfoCondition AgentInfoCondition, int PageSize, int PageIndex, ref int RecordCount, ref string msg);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AgentInfoCondition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int userIDField;
        
        private int loginUserIDField;
        
        private string trueNameField;
        
        private string aDNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int LoginUserID {
            get {
                return this.loginUserIDField;
            }
            set {
                this.loginUserIDField = value;
                this.RaisePropertyChanged("LoginUserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TrueName {
            get {
                return this.trueNameField;
            }
            set {
                this.trueNameField = value;
                this.RaisePropertyChanged("TrueName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ADName {
            get {
                return this.aDNameField;
            }
            set {
                this.aDNameField = value;
                this.RaisePropertyChanged("ADName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetCallRecordListSoapChannel : BitAuto.ISDC.CC2012.WebService.GetAgentInfo.ServiceReference.GetCallRecordListSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCallRecordListSoapClient : System.ServiceModel.ClientBase<BitAuto.ISDC.CC2012.WebService.GetAgentInfo.ServiceReference.GetCallRecordListSoap>, BitAuto.ISDC.CC2012.WebService.GetAgentInfo.ServiceReference.GetCallRecordListSoap {
        
        public GetCallRecordListSoapClient() {
        }
        
        public GetCallRecordListSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetCallRecordListSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetCallRecordListSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetCallRecordListSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetCallRecordByMaxID(string Verifycode, int maxID, ref string msg) {
            return base.Channel.GetCallRecordByMaxID(Verifycode, maxID, ref msg);
        }
        
        public int UpdateBusinessDataByCallID(string Verifycode, long callID, string businessID, int BGID, int SCID, int createuserid, ref string msg) {
            return base.Channel.UpdateBusinessDataByCallID(Verifycode, callID, businessID, BGID, SCID, createuserid, ref msg);
        }
        
        public System.Data.DataTable GetAgentInfoByBGID(string Verifycode, int LoginUserID, string TrueName, int PageSize, int PageIndex, ref int RecordCount, ref string msg) {
            return base.Channel.GetAgentInfoByBGID(Verifycode, LoginUserID, TrueName, PageSize, PageIndex, ref RecordCount, ref msg);
        }
        
        public string GetAgentRoleNameByDomainAccount(string Verifycode, string domainAccount) {
            return base.Channel.GetAgentRoleNameByDomainAccount(Verifycode, domainAccount);
        }
        
        public System.Data.DataTable GetAgentInfo(string Verifycode, int UserID, string ADName, ref int RecordCount, ref string msg) {
            return base.Channel.GetAgentInfo(Verifycode, UserID, ADName, ref RecordCount, ref msg);
        }
        
        public System.Data.DataTable GetAgentInfoByCondition(string Verifycode, BitAuto.ISDC.CC2012.WebService.GetAgentInfo.ServiceReference.AgentInfoCondition AgentInfoCondition, int PageSize, int PageIndex, ref int RecordCount, ref string msg) {
            return base.Channel.GetAgentInfoByCondition(Verifycode, AgentInfoCondition, PageSize, PageIndex, ref RecordCount, ref msg);
        }
    }
}
