//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCConsole.VCLogService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.voicecodes.com/", ConfigurationName="VCLogService.IVCLogService")]
    public interface IVCLogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/GetVoiceIPByVoiceID", ReplyAction="http://www.voicecodes.com/IVCLogService/GetVoiceIPByVoiceIDResponse")]
        string GetVoiceIPByVoiceID(int voiceid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/GetVoiceCount", ReplyAction="http://www.voicecodes.com/IVCLogService/GetVoiceCountResponse")]
        int GetVoiceCount(ref int[] voiceid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/GetChannelCountVoiceID", ReplyAction="http://www.voicecodes.com/IVCLogService/GetChannelCountVoiceIDResponse")]
        int GetChannelCountVoiceID(int voiceid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/GetRefID", ReplyAction="http://www.voicecodes.com/IVCLogService/GetRefIDResponse")]
        string GetRefID(string extention);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/GetFileHttpPath", ReplyAction="http://www.voicecodes.com/IVCLogService/GetFileHttpPathResponse")]
        string GetFileHttpPath(string RefID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/SaveRecordFile", ReplyAction="http://www.voicecodes.com/IVCLogService/SaveRecordFileResponse")]
        string SaveRecordFile(string RecordReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/GetRecordArchiveStatus", ReplyAction="http://www.voicecodes.com/IVCLogService/GetRecordArchiveStatusResponse")]
        string GetRecordArchiveStatus(string RecordReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/UpdateRecordDataExt", ReplyAction="http://www.voicecodes.com/IVCLogService/UpdateRecordDataExtResponse")]
        int UpdateRecordDataExt(string Extension, string Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/UpdateRecordDataByID", ReplyAction="http://www.voicecodes.com/IVCLogService/UpdateRecordDataByIDResponse")]
        int UpdateRecordDataByID(string RefID, string Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/UpdateRecordDataByUCID", ReplyAction="http://www.voicecodes.com/IVCLogService/UpdateRecordDataByUCIDResponse")]
        int UpdateRecordDataByUCID(string UCID, string Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/GetRecordListByStartRecordTime", ReplyAction="http://www.voicecodes.com/IVCLogService/GetRecordListByStartRecordTimeResponse")]
        string GetRecordListByStartRecordTime(string from, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/GetRecordList", ReplyAction="http://www.voicecodes.com/IVCLogService/GetRecordListResponse")]
        string GetRecordList(string from, string end, string JsonOtherConditions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/GetChannelByExt", ReplyAction="http://www.voicecodes.com/IVCLogService/GetChannelByExtResponse")]
        string GetChannelByExt(string Extension);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/StartRecord", ReplyAction="http://www.voicecodes.com/IVCLogService/StartRecordResponse")]
        int StartRecord(string Extension, string Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/StopRecord", ReplyAction="http://www.voicecodes.com/IVCLogService/StopRecordResponse")]
        int StopRecord(string Extension, string Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/PauseRecord", ReplyAction="http://www.voicecodes.com/IVCLogService/PauseRecordResponse")]
        int PauseRecord(string Extension, string Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/ResumeRecord", ReplyAction="http://www.voicecodes.com/IVCLogService/ResumeRecordResponse")]
        int ResumeRecord(string Extension, string Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/AgentLogin", ReplyAction="http://www.voicecodes.com/IVCLogService/AgentLoginResponse")]
        int AgentLogin(string Extension, string AgentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.voicecodes.com/IVCLogService/Agentlogout", ReplyAction="http://www.voicecodes.com/IVCLogService/AgentlogoutResponse")]
        int Agentlogout(string Extension);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVCLogServiceChannel : RCConsole.VCLogService.IVCLogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VCLogServiceClient : System.ServiceModel.ClientBase<RCConsole.VCLogService.IVCLogService>, RCConsole.VCLogService.IVCLogService {
        
        public VCLogServiceClient() {
        }
        
        public VCLogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VCLogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VCLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VCLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetVoiceIPByVoiceID(int voiceid) {
            return base.Channel.GetVoiceIPByVoiceID(voiceid);
        }
        
        public int GetVoiceCount(ref int[] voiceid) {
            return base.Channel.GetVoiceCount(ref voiceid);
        }
        
        public int GetChannelCountVoiceID(int voiceid) {
            return base.Channel.GetChannelCountVoiceID(voiceid);
        }
        
        public string GetRefID(string extention) {
            return base.Channel.GetRefID(extention);
        }
        
        public string GetFileHttpPath(string RefID) {
            return base.Channel.GetFileHttpPath(RefID);
        }
        
        public string SaveRecordFile(string RecordReference) {
            return base.Channel.SaveRecordFile(RecordReference);
        }
        
        public string GetRecordArchiveStatus(string RecordReference) {
            return base.Channel.GetRecordArchiveStatus(RecordReference);
        }
        
        public int UpdateRecordDataExt(string Extension, string Data) {
            return base.Channel.UpdateRecordDataExt(Extension, Data);
        }
        
        public int UpdateRecordDataByID(string RefID, string Data) {
            return base.Channel.UpdateRecordDataByID(RefID, Data);
        }
        
        public int UpdateRecordDataByUCID(string UCID, string Data) {
            return base.Channel.UpdateRecordDataByUCID(UCID, Data);
        }
        
        public string GetRecordListByStartRecordTime(string from, string end) {
            return base.Channel.GetRecordListByStartRecordTime(from, end);
        }
        
        public string GetRecordList(string from, string end, string JsonOtherConditions) {
            return base.Channel.GetRecordList(from, end, JsonOtherConditions);
        }
        
        public string GetChannelByExt(string Extension) {
            return base.Channel.GetChannelByExt(Extension);
        }
        
        public int StartRecord(string Extension, string Data) {
            return base.Channel.StartRecord(Extension, Data);
        }
        
        public int StopRecord(string Extension, string Data) {
            return base.Channel.StopRecord(Extension, Data);
        }
        
        public int PauseRecord(string Extension, string Data) {
            return base.Channel.PauseRecord(Extension, Data);
        }
        
        public int ResumeRecord(string Extension, string Data) {
            return base.Channel.ResumeRecord(Extension, Data);
        }
        
        public int AgentLogin(string Extension, string AgentID) {
            return base.Channel.AgentLogin(Extension, AgentID);
        }
        
        public int Agentlogout(string Extension) {
            return base.Channel.Agentlogout(Extension);
        }
    }
}
